export const restaurants = [
    {
      id: 1,
      name: "Butter Chicken",
      rating: 4.8,
      time: "45 minutes",
      cuisine: "Indian",
      img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/butter-chicken.jpg",
    },
    {
      id: 2,
      name: "Sushi Rolls",
      rating: 4.7,
      time: "50 minutes",
      cuisine: "Japanese",
      img: "https://www.japancentre.com/images/articles/440/large/maki-rolled-sushi-main.jpg",
    },
    {
      id: 3,
      name: "Margherita Pizza",
      rating: 4.6,
      time: "30 minutes",
      cuisine: "Italian",
      img: "https://www.seriouseats.com/thmb/9J2mjHP-3mgPUr1-JjeXtJtn96o=/1500x1125/filters:fill(auto,1)/20210321-skillet-margherita-pizza-melissa-hom-seriouseats-8-fb1e5a164b4740b2a6ad09f6e55a25d2.jpg",
    },
    {
      id: 4,
      name: "Tacos Al Pastor",
      rating: 4.9,
      time: "35 minutes",
      cuisine: "Mexican",
      img: "https://www.simplyrecipes.com/thmb/Zkz3x10sT2c5uMJUIu8sqg0GCMU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Tacos-Al-Pastor-LEAD-02-8014ef1e854747cc88eab4ef84e155a3.jpg",
    },
    {
      id: 5,
      name: "Burger",
      rating: 4.5,
      time: "25 minutes",
      cuisine: "Thai",
      img: "https://hot-thai-kitchen.com/wp-content/uploads/2020/06/pad-thai.jpg",
    },
    {
      id: 6,
      name: "French Onion Soup",
      rating: 4.4,
      time: "40 minutes",
      cuisine: "French",
      img: "https://www.simplyrecipes.com/thmb/huK05a8L-cv6FJ5D9NIBJc30jcw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-French-Onion-Soup-LEAD-3caa91bc4ddf4482a17632f2dc46ffec.jpg",
    },
    {
      id: 7,
      name: "Shakshuka",
      rating: 4.6,
      time: "30 minutes",
      cuisine: "Middle Eastern",
      img: "https://www.daringgourmet.com/wp-content/uploads/2021/01/Shakshuka-Recipe-2.jpg",
    },
    {
      id: 8,
      name: "Bibimbap",
      rating: 4.8,
      time: "35 minutes",
      cuisine: "Korean",
      img: "https://www.koreanbapsang.com/wp-content/uploads/2018/06/Bibimbap-Recipe.jpg",
    },
  ];
  